### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by arjunadhikary** [arjunadhikary/Hacktoberfest#71]
**This site needs to be responsive**

**Comment by prakhartech** [comment]
Hey, @arjunadhikary please assign me this I would love to do this.

**Comment by arjunadhikary** [comment]
Thanks for your interest 
Gotcha

**Comment by mindexpert7546** [comment]
Can you assign me .

**Comment by arjunadhikary** [comment]
Done

**Comment by iakshatgandhi** [comment]
i am also interseted in this

**Comment by arjunadhikary** [comment]
i could add you but two peoples are already seems to be working in the responsiveness 
if you still loved to do it you can again reply. but for now I am closing your issues
